### ISSUE TITLE
Update on my dad

### ISSUE THREAD

**Issue by joshpetrin** [forthefamilies/website#1]
Okie guys my dad’s okay. We’re not sure what happened but he was suddenly feeling faint at the YMCA and he threw up a few times. They were worried about his heart but they ran some tests and as far as they can tell he’s fine. It may have been something he ate. I think I’m going to stay with him tonight though. Good luck in the review! I think I left you guys with a good skeleton for all the webpages.

**Comment by Kaleab-Gebremichael** [comment]
Good to hear. We'll update you on what happens

**Comment by conrad1451** [comment]
Thank you for the update, we're glad your dad is doing ok. And thanks for the skeleton of the webpages, we were able to build off them and finish.
